name: natural_20
description: Encyclopedia, character management, and assistant app for Dungeons & Dragons 5e

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  firebase_database: ^9.0.14
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  firebase_storage: ^10.2.16
  splash_screen_view: ^3.0.0
  auth_buttons: ^2.0.4
  google_sign_in: ^5.3.1
  flutter_facebook_auth: ^4.3.4
  http: ^0.13.4
  animated_radial_menu: ^0.0.1
  flutter_form_builder: 7.2.0
  form_builder_validators: ^8.1.1
  file_picker: ^4.5.1
  provider: ^6.0.3
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

